### ISSUE TITLE
Duplicate of josh/CustomElements

### ISSUE THREAD

**Issue by josh** [pennyfx/customelements-polyfill#1]
Does this repository do anything different than the `CustomElements` package I have on github.com/josh/CustomElements? Its already registered to `CustomElements`

```
$ bower search CustomElements
Search results:

    CustomElements git://github.com/josh/CustomElements.git
    customelements-polyfill git://github.com/pennyfx/customelements-polyfill.git
```

**Comment by pennyfx** [comment]
I created a new repo because I needed full control over it to make it compatible with http://x-tags.org/download.   I made a few changes to bower.json, like adding a dependency for IE9 and updating keywords and description.  Not sure if you would approve of those changes and we at X-Tag may need to do other changes in the future as well.  I also wrapped ShadowDOM, HTMLImports, and Dom-Token-list so that we can ensure all of these libraries work perfectly with X-Tag.

**Comment by josh** [comment]
>  I made a few changes to bower.json, like adding a dependency for IE9 and updating keywords and description.

Sounds reasonable.

> Dom-Token-list

have you seen https://github.com/components/classList.js? Its published as `classlist` on bower. Does `CustomElements` need classList as a direct dependency?

I know `CustomElements` is under my profile right now, but I have no problem moving it over to `components/` if you want to co-maintain it. I feel like the web components community would be best off if we could standardize around the same core bower packages.

**Comment by pennyfx** [comment]
Dom-Token-List and classList look like they do the same thing.  I may switch to that dependency if all our tests pass.   It may be possible to make classList a dependency of x-tag/core instead of CustomElement and still get IE9 compatibility.  I'll have to test that too.   

I agree that having multiple copies of these libraries in Bower is not a good way to go and `components/` seems to be the right home for all of these Polyfills.   As long as I can resolve the dependencies correctly for X-Tag and add the appropriate metadata, then I'm all for it.

**Comment by josh** [comment]
Okay, I moved these repos over to the components org.

https://github.com/components/WeakMap
https://github.com/components/MutationObserver
https://github.com/components/CustomElements

Could we standardize the ShadowDOM and HTMLImports packages as well?

(btw, I work at GitHub so I can help you transfer repos to other orgs if you need too. I also have db admin access to the bower register if you need to cleanup or rename any bower packages.)

**Comment by pennyfx** [comment]
Sure, lets do it.  

Do you like the format of [HTMLImports](https://github.com/pennyfx/htmlimports-polyfill) and [ShadowDOM](https://github.com/pennyfx/shadowdom-polyfill) repo?  

I use git submodules to reference the original library and then a Grunt task to concat them into `/src/`.    These repos were created by a yeoman X-Tag component generator, so they can be cleaned up a little.   `demo/` isn't really used, so that can be removed.  There are a few Grunt tasks that probably aren't necessary.   I'm also thinking about moving the compiled source to the root directory.

EDIT:  Actually, html-imports has a demo and it looks like the grunt tasks are helpful.  I'll leave them alone.

Here are the Bower entries that need to be updated.

```
htmlimports-polyfill git://github.com/pennyfx/htmlimports-polyfill.git
shadowdom-polyfill git://github.com/pennyfx/shadowdom-polyfill.git
```

**Comment by josh** [comment]
I don't really have any strong opinions on the maintaining side. I mostly just care about having a single production ready concatenated file set as the bower `main`.

These strange development mode loaders the Polymer team has set as `main` aren't useful and require all sorts of parent directories to be setup.

https://github.com/Polymer/CustomElements/blob/master/custom-elements.js
https://github.com/Polymer/ShadowDOM/blob/master/shadowdom.js

**Comment by josh** [comment]
Do you need me to create the `components/ShadowDOM` and `components/HTMLImports` repositories to start off?

**Comment by pennyfx** [comment]
Those polymer loaders are the exact reason I created these repos. 

Yes, can you create the repos for me?  I not part of that Org yet.

**Comment by josh** [comment]
Created.

https://github.com/components/ShadowDOM
https://github.com/components/HTMLImports

**Comment by pennyfx** [comment]
I want to blow out the contents of those repos and reference the original repo via git submodule.  Is that cool?  I feel like these repos should be shims, not full clones.

**Comment by josh** [comment]
Thats cool. I just wanted the fork reference back to the original Polymer repo.

**Comment by pennyfx** [comment]
K, I updated ShadowDOM, HTMLImports, and CustomElement repos. 

Can you easily delete tags since you're on the Github side of things?  If so, can you remove all the tags on these repos except 0.2.3?  I don't want anyone to accidentally use an old tag that doesn't support these new conventions.

**Comment by josh** [comment]
> Can you easily delete tags since you're on the Github side of things? If so, can you remove all the tags on these repos except 0.2.3? I don't want anyone to accidentally use an old tag that doesn't support these new conventions.

Done.

**Comment by josh** [comment]
Thanks!

I'll close this issue out. We have have more specific discussions on the repos themselves.
